experiments:

    num_robots: 2
    robot_id: 1
    robot_id: 2
    num_tests: 10
  - test: 1
    map_known: office_known.pgm
    map_unknown: office_unknown1.pgm
  - test: 2
    map_known: office_known.pgm
    map_unknown: office_unknown2.pgm
  - test: 3
    map_known: office_known.pgm
    map_unknown: office_unknown3.pgm
  - test: 4
    map_known: office_known.pgm
    map_unknown: office_unknown4.pgm
  - test: 5
    map_known: office_known.pgm
    map_unknown: office_unknown5.pgm
  - test: 6
    map_known: office_known.pgm
    map_unknown: office_unknown6.pgm
  - test: 7
    map_known: office_known.pgm
    map_unknown: office_unknown7.pgm
  - test: 8
    map_known: office_known.pgm
    map_unknown: office_unknown8.pgm
  - test: 9
    map_known: office_known.pgm
    map_unknown: office_unknown9.pgm
  - test: 10
    map_known: office_known.pgm
    map_unknown: office_unknown10.pgm
